### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by htn274** [Syphdias/i3-chrome-tab-dragging#4] opened 2022-01-09 09:15 UTC
![image](https://user-images.githubusercontent.com/26211514/148676293-e9272ccf-8fe1-4fd4-b592-51f70816b450.png)
I am very appreciate for your work cause it is very helpful for me if it would work. 
This is my screenshot for i3 config. 
I don't know why it does not work. 
I hope to have your help.
Thank you!

**Comment by Syphdias** [comment] 2022-01-09 10:38
Did you install the requirements? `pip install --user -r requirements.txt`

Also, could you try running `~/.config/i3/i3-chrome-tab-dragging.py` directly in the commandline to see any errors?

**Comment by htn274** [comment] 2022-01-10 00:41
![ezgif com-gif-maker](https://user-images.githubusercontent.com/26211514/148707771-97a9eabd-6067-4827-a59f-9f976a91d290.gif)
It doesn''t show any error. So I don't know what is happening  :<

**Comment by Syphdias** [comment] 2022-01-10 22:25
So I think we need to talk a bit more precise.
The problem this script is supposed to solve is, that if you take one tab ob Google Chrome while using the i3wm it instantly resizes the dragged tag to a tiling window. This means that is takes up half the space of in a usual configuration.

The script listens for new Chrome window events and if at this time the (left) mouse button is pressed, it switches the window to floating. You can then drag the window as you normally would.
In your demonstration it looks like this is working fine.

If you release the window that was just created, it will go back to non-floating, unless it does not exist anymore. This happens if you move it into another Google Chrome window. It looks like this is what is not working correctly right? Can you make sure you see the tab in the window before letting go of the mouse button?

**Comment by tjb0607** [comment] 2022-01-12 19:26
this is an upstream issue that has nothing to do with this script, a recent update somehow broke all drag and drop functionality in Chrome in i3 and it seems like htn274 was hoping this script could fix that issue. Unfortunately, this script is a fix for a completely different issue.

**Comment by Syphdias** [comment] 2022-01-12 20:21
Yup, I can now (unhappily) say, that I have the same issue.

My Chromium is still on version 96; here the dragging is broken in a way this script can workaround it.
My Google Chrome is on version 97; here it is broken the way ~you~ we experience.

I didn't search for a chromium issue yet?

PS: Actually dragging windows used to work in version 83 of chromium/chrome and somehow it broke...

**Comment by Syphdias** [comment] 2022-01-12 20:27
https://bugs.chromium.org/p/chromium/issues/detail?id=1286852&q=drag&can=2

Edit: This is just one of many issues you find if you search the bugtracker for "drag"
Edit2: This seems to be the main one: https://bugs.chromium.org/p/chromium/issues/detail?id=1279532

**Comment by htn274** [comment] 2022-01-17 00:45
Thank you for your support. I have changed to Firefox recently :laughing:  
I think the issue is from chrome not from your code. But I wonder can I downgrade the google chrome? :thinking:

**Comment by Syphdias** [comment] 2022-01-17 23:05
I'll close this issue but leave it pinned, just in case someone stumbles into the same issue.

I also added to the README at the top after the deprecation warning which versions broke stuff.

**Closed as completed by Syphdias** 2022-01-17 23:05 UTC

**Comment by cseyda** [comment] 2022-01-20 22:13
Version 97.0.4692.99 of Chromium fixed the drag problem for me

**Comment by Syphdias** [comment] 2022-01-22 14:28
"Fixed". Let's just say it makes sense to use this repo/script/tool again.
To recap:
- pre 83.x: Dragging is not working flawlessly, this tool was born
- 83.x–95.0.4630.0: Perfect window dragging, no tool assist needed
- 95.0.4630.0–97.0.4692.99: Major breakage in dragging, this tool cannot fix it
- 97.0.4692.99+: Dragging works like pre 83.x again, tool can work again

**Comment by ekzyis** [comment] 2022-06-04 16:01
Mhh, can you confirm it is still working? Going into floating mode on dragging seems to work but the tab does not dock into the other window for some reason.

I am using Google Chrome Version 102.0.5005.61 (Official Build) (64-bit) with i3 version 4.20.1 (2021-11-03) and 5.10.117-1-MANJARO.

Thanks for your work btw!

**Comment by tjb0607** [comment] 2022-06-04 23:09
there was an upstream regression (https://bugs.chromium.org/p/chromium/issues/detail?id=1279532#c162) which specifically affects i3, a fix is on the way (https://chromium.googlesource.com/chromium/src/+/95b94a2b841b624be8c0c99730f7011aa56a6a60) but you have to wait for the next chrome release

**Comment by Syphdias** [comment] 2022-06-08 21:50
Unfortunately, [the issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1279532) has been fixed (partly) multiple times now before getting broken again. :disappointed:
